apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmss-rg14-start
  labels:
    app: recycle-vmss-rg14-start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recycle-vmss-rg14-start
  template:
    metadata:
      labels:
        app: recycle-vmss-rg14-start
    spec:
      containers:
      - name: recycle-vmss-rg14-start
        image: grakslab.azurecr.io/recycle-vmss:latest
        imagePullPolicy: Always
        env:
        - name: AzureWebJobsStorage
          value: ""
        - name: WEBSITE_TIME_ZONE
          value: "America/Vancouver"
        - name: FUNCTIONS_WORKER_RUNTIME
          value: "dotnet"
        - name: AZURE_AD_TENANT_ID
          value: ""
        - name: AZURE_AD_TOKEN_EP
          value: ""
        - name: AZURE_SP_CLIENT_ID
          value: ""
        - name: AZURE_SP_CLIENT_SECRET
          value: ""
        - name: AZURE_SP_APP_ID_URI
          value: "https://management.azure.com"
        - name: AZURE_SUBSCRIPTION_ID
          value: ""
        - name: AZURE_RES_GROUP_NAME
          value: ""
        - name: AZURE_VMSS_NAME
          value: ""
        - name: AZURE_VMSS_API_VER
          value: "2019-12-01"
        - name: VmssTriggerSchedule
          value: "0 0 8 * * Mon"
        - name: AZURE_VMSS_ACTION
          value: "start"
      nodeSelector:
        kubernetes.io/os: linux
